# Generated by Django 5.2.6 on 2025-09-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
